### ISSUE TITLE
Use tempname() instead of hardcoding ~/local/share/nvim?

### ISSUE THREAD

**Issue by MultisampledNight** [smzm/hydrovim#2]
Hi, this looks like an insanely cool plugin!

I was taking a short peek at the code and wondering, is `~/local/share/nvim/plugged` safe to use? Do note the missing dot before `local`, according to the [XDG base directory spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables) the default is _with_ dot. Also I'm not quite sure if `plugged` is safe to use, someone might have their plugins entirely elsewhere (e.g. in the immutable Nix store).

Therefore I think it might be more safe to use the `tempname()` Vim function and carry the filenames over in variables, which should also work on NixOS, custom plugin directories, changed `$XDG_DATA_HOME`s...

**Comment by smzm** [comment]
**Yes, you're right.**
Apart from the correct path, there are absolute paths that are wired by themselves. that's because for a long time, I use this code just for myself and I forgot to change the paths after publishing it on Github.
By the way, I hadn't seen `tempname()` before. *Your offer is greatly appreciated.*
